CREATE DATABASE IF NOT EXISTS passwords;

USE passwords;

CREATE TABLE IF NOT EXISTS passwords (
    id INT(11) NOT NULL AUTO_INCREMENT,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;